baseURL = "https://crypto-easy.org/"
languageCode = "en"
title = "Crypto Easy"
hugoVersion = "0.159.1"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableRobotsTXT = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"

  [languages.ru]
    weight = 2
    languageName = "Русский"

  [languages.fr]
    weight = 3
    languageName = "Français"

[params]
  description = "Crypto is Easy"

[menu]

  [[menu.main]]
    identifier = "learn"
    url = "/learn/"
    weight = 1

  [[menu.main]]
    identifier = "tools"
    url = "/tools/"
    weight = 2

  [[menu.main]]
    identifier = "make_money"
    url = "/make-money/"
    weight = 3

  [[menu.main]]
    identifier = "security"
    url = "/security/"
    weight = 4

  [[menu.main]]
    identifier = "reviews"
    url = "/reviews/"
    weight = 5

  [[menu.main]]
    identifier = "glossary"
    url = "/glossary/"
    weight = 6

[params.analytics]
  ga4 = "G-YBDQ33HB6Z"
  yandexMetrica = "108580611"
