baseURL = "https://crypto-easy.org/"
languageCode = "en"
title = "Crypto Easy"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    weight = 1
    languageName = "EN"

  [languages.ru]
    weight = 2
    languageName = "RU"

  [languages.fr]
    weight = 3
    languageName = "FR"

[params]
  description = "Crypto is Easy"